CarTuningForum/Models/ErrorViewModel.cs
using System;

namespace CarTuningForum.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarTuningForum/Controllers/ForumController.cs
using CarTuningForum.Service.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarTuningForum.Web.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForumService _forumService;
        private readonly IPostService _postService;
        private readonly ICommentService _commentService;
        public ForumController(IForumService forumService, IPostService postService, ICommentService commentService)
        {
            _forumService = forumService;
            _postService = postService;
            _commentService = commentService;
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

CarTuningForum/Controllers/HomeController.cs
using CarTuningForum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CarTuningForum.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarTuningForum/Controllers/PostController.cs
using CarTuningForum.DTOs.IndexList;
using CarTuningForum.DTOs;
using CarTuningForum.Service.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using CarTuningForum.Models;
using Microsoft.AspNetCore.Identity;
using CarTuningForum.ViewModels;
using System.Threading.Tasks;
using System.Security.Claims;
using System;
using CarTuningForum.ViewModels.Mappers;

namespace CarTuningForum.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IForumService _forumService;
        private readonly IPostService _postService;
        //private readonly UserManager<User> _userManager;
        IUserService _userManager;
        public PostController(IForumService forumService, IPostService postService, /*UserManager<User> */IUserService userManager)
        {
            _forumService = forumService;
            _postService = postService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            try
            {
                IEnumerable<PostDTO> postsDTO = _forumService.GetAllPosts();

                var posts = new PostIndex
                {
                    PostList = postsDTO
                };
                return View(model: posts);
            }
            catch (System.NullReferenceException)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                return View();
            }
        }

        public IActionResult Details(int postId)
        {
            var post = _forumService.GetPostById(postId);
            var comments = _forumService.GetAllPostComments(postId);

            return View(model: post);
        }
        //public IActionResult Like(string userId, int postId)
        //{
        //    this._forumService.LikePost(userId, postId);
        //    return Ok();
        //}
        //public IActionResult Create()
        //{
        //    var postDTO = new PostDTO();
        //    var model = new NewPostModel
        //    {
        //        Title = postDTO.Title,
        //        Author = postDTO.Author.FirstName + " " + postDTO.Author.LastName,
        //        Content = postDTO.Content,
        //        PostId = postDTO.Id,
        //    };
        //    return View(model);
        //}
        //[HttpPost]
        //public async Task<IActionResult> AddPost(NewPostModel model)
        //{
        //    //var userId = this._userManager.GetUser
        //    //var user = await this._userManager.FindByIdAsync(userId);
        //    var postDTO = BuildPost(model);

        //    await this._postService.Create(postDTO);

        //    return RedirectToAction("Details", "Post", postDTO.Id);
        //}

        //private PostDTO BuildPost(NewPostModel model)
        //{
        //    return new PostDTO
        //    {
        //        Title = model.Title,
        //        Content = model.Content,
        //        CreatedOn = DateTime.Now,
        //        //Author = user
        //    };
        //}
    }
}

CarTuningForum/Controllers/UserController.cs
using CarTuningForum.Models;
using CarTuningForum.Service.Contracts;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarTuningForum.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Details(string userId)
        {
            var user = this._userService.GetUser(userId);
            return View(model: user);
        }
        //public IActionResult Login()
        //{
            
        //}
    }
}

CarTuningForum/Views/Comment/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CarTuningForum/Views/Home/Index.cshtml
@model CarTuningForum.DTOs.IndexList.PostIndex
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4 class="display-2">Welcome</h4>
    <img src="~/images/ecuTuningBanner.jpg" />
    <h4 class="display-4">10 Most Recent Posts</h4>
   

</div>

CarTuningForum/Views/Post/Details.cshtml
@model CarTuningForum.DTOs.PostDTO
<h1>@Model.Title</h1>
<div>
    Author: @Model.Author.UserName
    Created: @Model.CreatedOn
</div>

<div>
    @Model.Content
</div>

@if (Model.Comments.Any())
{
    foreach (var com in Model.Comments)
    {
        <div>

            <div>
                Comment Author: @com.Author.FirstName @com.Author.LastName
                Comment Created: @com.CreatedOn
            </div>

            <div>
                Comment: @com.Message
            </div>
            
        </div>
    }
}

CarTuningForum/Views/Post/Index.cshtml
@model CarTuningForum.DTOs.IndexList.PostIndex

<div>

    <h1>Posts</h1>
    @if (Model.PostList.Any())
    {
        <table class="table table-hover" id="postIndexTable">
            <tbody>
                @foreach (var post in Model.PostList)
                {
                    <tr>
                        <td>
                            <a asp-controller="Post" asp-action="Topic" asp-route-id="@post.Id">
                                @post.Title

                            </a>
                        </td>
                        <td>
                                <a asp-controller="User" asp-action="User" asp-route-id="@User.Identity">
                                    @post.Author

                                </a>
                            </td>
                        <td>
                            @post.Content
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    }
    else
    {
        <div class="noPosts">
        <h3>It looks like there are no posts yet.</h3><br />
            Why not
            <a asp-controller="Post" asp-action="Create">
                <span>create</span>
            </a>
            one?
        </div>

    }
</div>

CarTuningForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarTuningForum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarTuningForum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CarTuningForum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

CarTuningForum/Views/User/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}